### ISSUE TITLE
nevents query with different instance doesn't seem to work, and print value as int instead of scientific notation?

### ISSUE THREAD

**Issue by jordantucker** [vkuznet/dasgoclient#4] opened 2017-01-28 20:48 UTC
Hi Valentin,

a query like 
"instance=prod/phys03 dataset=/GluinoGluinoToNeutralinoNeutralinoTo2T2B2S_M-1600_CTau-300um_TuneCUETP8M1_13TeV-pythia8/tucker-NtupleV10-8b38292c5b8bb33a99eba28cc8240b1d/USER | grep dataset.nevents"

doesn't seem to work with dasgoclient, while if I query a different dataset in prod/global (so no instance= string in the query) it works.

(Although it returns the number in scientific notation--maybe just print the int?)

Thanks,
Jordan

**Comment by vkuznet** [comment] 2017-01-28 22:02
Jordan,
thanks for report, the issue is missing select keys of your DAS query, you're
saying instance=bla dataste=bla but don't specify what you want from these
conditions. The correct query should be:

dataset dataset=/GluinoGluinoToNeutralinoNeutralinoTo2T2B2S_M-1600_CTau-300um_TuneCUETP8M1_13TeV-pythia8/tucker-NtupleV10-8b38292c5b8bb33a99eba28cc8240b1d/USER instance=prod/phys03 | grep dataset.nevents

which says, select dataset from conditions and apply a filter. It will work.

But there is still some issue with DAS QL implementation which I need to fix,
i.e. the order is matter. I'll have a look.

Best,
Valentin.

**Comment by vkuznet** [comment] 2017-02-02 23:50
Jordan, I updated the code which returns a meaningful message if user does not specify select key in DAS query. The binaries are updated on lxplus. I'm closing the ticket.

**Closed by vkuznet** 2017-02-02 23:50 UTC
