### ISSUE TITLE
Number of events as int

### ISSUE THREAD

**Issue by andresti** [vkuznet/dasgoclient#5] opened 2017-02-06 23:47 UTC
Hi Valentin,

As was suggested already in #4,
I'd also prefer seeing int values in output as ints, not in scientific notation, especially for number of events.
e.g. not:{"file_size":2.10136229489e+11,"nblocks":24,"nevents":6.669988e+06,"nfiles":96,"nlumis":34502,"num_block":24,"num_event":6.669988e+06,"num_file":96,"num_lumi":34502}
but: "nevents":6669988e and so on.

Thanks,
Andres

**Comment by vkuznet** [comment] 2017-02-07 13:29
Andres, could you please post exact query you did that I can reproduce and work on that issue.

**Comment by vkuznet** [comment] 2017-02-07 15:26
Andres, I really need an example of the query, since for dataset I'm querying I don't see this behavior, e.g.
```
./dasgoclient -query="summary dataset=/ZMM/Summer11-DESIGN42_V11_428_SLHC1-v1/GEN-SIM"
{"file_size":5.658838455e+09,"nblocks":1,"nevents":7398,"nfiles":6,"nlumis":16,"num_block":1,"num_event":7398,"num_file":6,"num_lumi":16}
```
I bet the problem is related to value of nevents in specific query, for small numbers (which probably fits into int32 boundaries the output print ints, while for large values it cast to float and report scientific notation). Once I'll have your specific query I can see where the problem is.

**Comment by andresti** [comment] 2017-02-07 17:04
Actually in your query you can see it happening for file_size.
But for example:
`dasgoclient_linux  -query="summary dataset=/ttHJetTobb_M125_13TeV_amcatnloFXFX_madspin_pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6_ext3-v1/MINIAODSIM"`

Anyhow, thanks for making the client, great to use something that works fast :)

**Comment by vkuznet** [comment] 2017-02-07 19:38
This should be fixed now, please try out new executables on AFS:
/afs/cern.ch/user/v/valya/public/dasgoclient/dasgoclient_linux
/afs/cern.ch/user/v/valya/public/dasgoclient/dasgoclient_osx

The actual fix went into: 
https://github.com/vkuznet/das2go/commit/6acaade41d3b2c916855d516af5435ad7a1cd8ba

**Comment by andresti** [comment] 2017-02-08 11:45
I don't know if it's related, but the new executable doesn't seem to work for me:
`/afs/cern.ch/user/v/valya/public/dasgoclient/dasgoclient_linux -query="summary dataset=/ttHJetTobb_M125_13TeV_amcatnloFXFX_madspin_pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6_ext3-v1/MINIAODSIM" `

> {"error":"DBS unable to unmarshal the data into DAS record, api=summary4dataset_run, data=, error=EOF"}

**Comment by vkuznet** [comment] 2017-02-08 12:22
Hi,
it works for me, I just checked on both OSX and Linux (lxplus). Could you
please try again, may be it was a DBS glitch.
Thanks,
Valentin.

**Comment by andresti** [comment] 2017-02-08 12:27
Indeed it works, I had to log out and in again. Thanks.

**Closed** 2017-02-08 12:27 UTC
